// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtjqoGtMdueJKphsewppIY2Zqq4_7Xpc',
    appId: '1:423664070781:web:ed157cb3cd4dff450b8114',
    messagingSenderId: '423664070781',
    projectId: 'fir-flutter-5bfec',
    authDomain: 'fir-flutter-5bfec.firebaseapp.com',
    storageBucket: 'fir-flutter-5bfec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5KOq7VXLjKPa2XQa3ue5vXA8fqlgHcQ',
    appId: '1:423664070781:android:749419697a796e9a0b8114',
    messagingSenderId: '423664070781',
    projectId: 'fir-flutter-5bfec',
    storageBucket: 'fir-flutter-5bfec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrNLBOOvmr8XyAfD3WUmnkuw4Sqm4DWVg',
    appId: '1:423664070781:ios:b8051761116a41bb0b8114',
    messagingSenderId: '423664070781',
    projectId: 'fir-flutter-5bfec',
    storageBucket: 'fir-flutter-5bfec.appspot.com',
    iosClientId: '423664070781-l2j5gn7r7pfquu2nrfdjpph543igfbvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrNLBOOvmr8XyAfD3WUmnkuw4Sqm4DWVg',
    appId: '1:423664070781:ios:b8051761116a41bb0b8114',
    messagingSenderId: '423664070781',
    projectId: 'fir-flutter-5bfec',
    storageBucket: 'fir-flutter-5bfec.appspot.com',
    iosClientId: '423664070781-l2j5gn7r7pfquu2nrfdjpph543igfbvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );
}
